name: Cross-Platform Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: |
          cargo clippy --all-targets --all-features --message-format=json -- -D warnings > clippy-output.json || true
          if command -v clippy-sarif &> /dev/null; then
            cat clippy-output.json | clippy-sarif | tee clippy-results.sarif | sarif-fmt
          else
            echo "clippy-sarif not installed, skipping SARIF conversion"
            cargo clippy --all-targets --all-features -- -D warnings
          fi

      - name: Upload clippy results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('clippy-results.sarif') != ''
        with:
          sarif_file: clippy-results.sarif
          wait-for-processing: true

      - name: Run tests
        run: cargo test --verbose --all-features

  build:
    name: Build
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: linux-x86_64
            
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: windows-x86_64
            
          - target: x86_64-apple-darwin
            os: macos-13
            name: macos-x86_64
            
          - target: aarch64-apple-darwin
            os: macos-latest
            name: macos-aarch64
            
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: linux-aarch64

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Install cross-compilation tools for Linux ARM64
      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Build binary
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Get binary name
        id: binary_name
        shell: bash
        run: |
          BINARY_NAME=$(grep '^name = ' Cargo.toml | head -n1 | cut -d '"' -f2)
          echo "binary_name=$BINARY_NAME" >> $GITHUB_OUTPUT
          echo "Binary name: $BINARY_NAME"

      - name: Strip binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          BINARY_PATH="target/${{ matrix.target }}/release/${{ steps.binary_name.outputs.binary_name }}"
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            aarch64-linux-gnu-strip "$BINARY_PATH"
          else
            strip "$BINARY_PATH"
          fi

      - name: Create archive
        shell: bash
        run: |
          BINARY_NAME="${{ steps.binary_name.outputs.binary_name }}"
          
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            BINARY_EXT=".exe"
          else
            BINARY_EXT=""
          fi
          
          mkdir -p release/${{ matrix.name }}
          cp "target/${{ matrix.target }}/release/${BINARY_NAME}${BINARY_EXT}" "release/${{ matrix.name }}/"
          
          if [ -f README.md ]; then
            cp README.md "release/${{ matrix.name }}/"
          fi
          if [ -f LICENSE ]; then
            cp LICENSE "release/${{ matrix.name }}/"
          fi
          
          cd release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a "../${{ matrix.name }}.zip" "${{ matrix.name }}"
          else
            tar czf "../${{ matrix.name }}.tar.gz" "${{ matrix.name }}"
          fi
          cd ..

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ matrix.name }}.tar.gz
            ${{ matrix.name }}.zip
          if-no-files-found: ignore

  release:
    name: Create Release
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*/*.tar.gz
            artifacts/*/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run security audit
        run: cargo audit

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          fail_ci_if_error: false

      - name: Coverage annotations
        run: |
          echo "## Code Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "Coverage report uploaded to Codecov" >> $GITHUB_STEP_SUMMARY
          
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run benchmarks
        run: |
          if cargo bench --help 2>/dev/null | grep -q "criterion"; then
            cargo bench --bench '*' 2>&1 | tee benchmark-results.txt || echo "Benchmarks failed"
            echo "## Benchmark Results" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            tail -20 benchmark-results.txt >> $GITHUB_STEP_SUMMARY || echo "No benchmark output" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "No benchmarks found (criterion not configured)"
            echo "## Benchmark Results" >> $GITHUB_STEP_SUMMARY
            echo "No benchmarks found (criterion not configured)" >> $GITHUB_STEP_SUMMARY
          fi

  annotations:
    name: PR Annotations
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [test, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate build summary
        run: |
          echo "## Rust Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Build Status" >> $GITHUB_STEP_SUMMARY
          echo "- All platform builds completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "- Tests passed" >> $GITHUB_STEP_SUMMARY
          echo "- Code formatting valid" >> $GITHUB_STEP_SUMMARY
          echo "- Clippy linting passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Available Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "- Linux x86_64" >> $GITHUB_STEP_SUMMARY
          echo "- Linux ARM64" >> $GITHUB_STEP_SUMMARY  
          echo "- Windows x86_64" >> $GITHUB_STEP_SUMMARY
          echo "- macOS x86_64" >> $GITHUB_STEP_SUMMARY
          echo "- macOS ARM64" >> $GITHUB_SUMMARY

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && comment.body.includes('Rust Build Report')
            );
            
            const body = `## Rust Build Report

# ### Summary
# - Cross-platform builds completed
# - Tests passed  
# - Code formatting valid
# - Clippy linting passed
# - Security audit clean

# ### Available Platforms
# | Platform | Status | Artifact |
# |----------|---------|----------|
# | Linux x86_64 | Passed | Available |
# | Linux ARM64 | Passed | Available |
# | Windows x86_64 | Passed | Available |
# | macOS x86_64 | Passed | Available |
# | macOS ARM64 | Passed | Available |

# Download artifacts from the [Actions tab](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})`;
            
#             if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }
